controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_endeffector_controller
    type: $(arg execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: qr_start
  - group: endeffector
    pose: close